version: '3.8'

services:
  app:
    # Override for development environment
    volumes:
      - .:/app  # Mount current directory to /app for development
      - ./models:/app/models  # Persist local LLM models
    environment:
      - DEVELOPMENT=true
    command: sh -c "python database_check.py && streamlit run app.py --server.port 5000"
    
  # Add tool to easily view database content
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db